local config = {}
-- -------------------
-- CONFIG
-- -------------------
config.TEMPLATE_DIR = "templates"
config.MATCH_THRESHOLD = 0.7
config.WIDE_MATCH_THRESHOLD = 0.85
config.WIDE_SCAN_INTERVAL = 3
config.STALL_DIAGNOSTIC_SECONDS = 20

-- -------------------
-- STAGE DETECTION TEMPLATES
-- -------------------
config.STAGE_MAINMENU_TEMPLATE = {"MAINMENU_1.png"}
config.STAGE_PURCHASE_ITEM_TEMPLATE = {"PURCHASE_ITEM_1.png"}
config.STAGE_GAME_START_TEMPLATE = {"GAME_START_1.png"}
config.STAGE_GAME_RELAY_TEMPLATE = {"GAME_RELAY_1.png"}
config.STAGE_GAME_COMPLETE_TEMPLATE = {"GAME_COMPLETE_1.png"}
config.STAGE_MYSTERY_BOX_TEMPLATE = {"MYSTERY_BOX_1.png"}
config.STAGE_CONGRATULATIONS_TEMPLATE = {"CONGRATULATIONS_1.png", "CONGRATULATIONS_2.png"}
config.STAGE_LEVEL_UP_TEMPLATE = {"LEVEL_UP_1.png"}
config.STAGE_RELIC_COMPLETE_TEMPLATE = {"RELIC_COMPLETE_1.png"}
config.STAGE_RELIC_CLAIM_TEMPLATE = {"RELIC_CLAIM_1.png"}
config.STAGE_DAILY_CHECKIN_TEMPLATE = {"DAILY_CHECKIN_1.png"}
config.STAGE_DAILY_CHECKIN_BOOST_SET_TEMPLATE = {"DAILY_CHECKIN_BOOST_SET_1.png"}
config.STAGE_DAILY_TREASURE_TEMPLATE = {"DAILY_TREASURE_1.png"}
config.STAGE_DAILY_NEW_TEMPLATE = {"DAILY_NEW_1.png"}
config.STAGE_ENTER_LEAGUE_TEMPLATE = {"ENTER_LEAGUE_1.png"}
config.STAGE_LEAGUE_RESULTS_TEMPLATE = {"LEAGUE_RESULTS_1.png"}
config.STAGE_ANTI_BOT_TEMPLATE = {"ANTI_BOT_1.png"}
config.STAGE_CONNECTION_LOST_TEMPLATE = {"CONNECTION_LOST_1.png", "CONNECTION_LOST_2.png"}
config.STAGE_INACTIVE_TEMPLATE = {"INACTIVE_1.png"}
config.STAGE_PREVIOUS_RANK_RESULTS_TEMPLATE = {"PREVIOUS_RANK_RESULTS_1.png"}
config.STAGE_TOO_MANY_TREASURES_TEMPLATE = {"TOO_MANY_TREASURES_1.png"}
config.STAGE_OVERTAKE_BREAK_SCORE_TEMPLATE = {"OVERTAKE_BREAK_SCORE_1.png"}
config.STAGE_PARTY_RUN_TEMPLATE = {"PARTY_RUN_1.png"}
config.STAGE_GAME_SETTINGS_TEMPLATE = {"GAME_SETTINGS_1.png"}

-- -------------------
-- STAGE DETECTION REGIONS
-- -------------------
-- Format: {x1, y1, x2, y2}
-- Allow mobile font/position differences around the Friends tab.
config.STAGE_MAINMENU_REGION = {114, 120, 394, 255}
config.STAGE_PURCHASE_ITEM_REGION = {474, 84, 602, 138}
config.STAGE_GAME_START_REGION = {573, 265, 733, 427}
config.STAGE_GAME_RELAY_REGION = {573, 265, 733, 427}
config.STAGE_GAME_COMPLETE_REGION = {523, 27, 757, 116}
config.STAGE_MYSTERY_BOX_REGION = {503, 46, 782, 107}
config.STAGE_CONGRATULATIONS_REGION = {372, 85, 909, 200}
config.STAGE_LEVEL_UP_REGION = {481, 34, 798, 130}
config.STAGE_RELIC_COMPLETE_REGION = {480, 63, 578, 106}
config.STAGE_RELIC_CLAIM_REGION = {412, 72, 865, 191}
config.STAGE_DAILY_CHECKIN_REGION = {491, 21, 792, 75}
config.STAGE_DAILY_CHECKIN_BOOST_SET_REGION = {523, 88, 754, 182}
config.STAGE_DAILY_TREASURE_REGION = {452, 117, 824, 161}
config.STAGE_DAILY_NEW_REGION = {432, 12, 849, 78}
config.STAGE_ENTER_LEAGUE_REGION = {318, 235, 962, 384}
config.STAGE_LEAGUE_RESULTS_REGION = {512, 52, 779, 105}
config.STAGE_ANTI_BOT_REGION = {309 - 5, 10 - 5, 968 + 10, 111 + 10}
config.STAGE_CONNECTION_LOST_REGION = {351, 203, 936, 405}
config.STAGE_INACTIVE_REGION = {358, 247, 934, 372}
config.STAGE_PREVIOUS_RANK_RESULTS_REGION = {454, 42, 832, 115}
config.STAGE_TOO_MANY_TREASURES_REGION = {350, 151, 934, 479}
config.STAGE_OVERTAKE_BREAK_SCORE_REGION = {479, 64, 799, 132}
config.STAGE_PARTY_RUN_REGION = {359, 44, 922, 138}
config.STAGE_GAME_SETTINGS_REGION = {484, 62, 769, 122}

-- -------------------
-- DETECTION TEMPLATES
-- -------------------
config.FRIEND_TOP_LEADERBOARD_TEMPLATE = {"FRIEND_TOP_LEADERBOARD_1.png"}
config.FRIEND_BOTTOM_LEADERBOARD_TEMPLATE = {"FRIEND_BOTTOM_LEADERBOARD_1.png"}
config.FRIEND_SEND_LIFE_TEMPLATE = {"FRIEND_SEND_LIFE_1.png"}
config.NO_LIVES_TO_RECEIVE_TEMPLATE = {"NO_LIVES_TO_RECEIVE_1.png"}
config.ALL_LIVES_RECEIVED_AND_SENT_TEMPLATE = {"ALL_LIVES_RECEIVED_AND_SENT_1.png"}
config.CONFIRM_SEND_LIFE_TEMPLATE = {"CONFIRM_SEND_LIFE_1.png"}

-- -------------------
-- DETECTION REGION
-- -------------------
-- Mobile banners can extend past the old right edge (1091), preventing a
-- full-template match even when the correct boost is visible.
config.RANDOM_BOOST_REGION = {650, 480, 1195, 590}
config.FRIEND_TOP_LEADERBOARD_REGION = {149, 272, 203, 574}
config.FRIEND_BOTTOM_LEADERBOARD_REGION = {272, 545, 610, 625}
config.FRIEND_SEND_LIFE_REGION = {608, 274, 721, 630}
config.NO_LIVES_TO_RECEIVE_REGION = {454, 223, 824, 575}
config.ALL_LIVES_RECEIVED_AND_SENT_REGION = {396, 267, 882, 346}
config.CONFIRM_SEND_LIFE_REGION = {640, 402, 944, 515}

-- -------------------
-- BOOST TEMPLATES
-- -------------------
config.BOOST_DOUBLE_COINS_TEMPLATE = {"BOOST_DOUBLE_COINS_1.png"}
config.BOOST_15P_SCORE_BONUS_TEMPLATE = {"BOOST_15P_SCORE_BONUS_1.png"}
config.BOOST_M15P_HP_DRAIN_TEMPLATE = {"BOOST_M15P_HP_DRAIN_1.png"}
config.BOOST_REVIVE_ONCE_WITH_80HP_TEMPLATE = {"BOOST_REVIVE_ONCE_WITH_80HP_1.png"}
config.BOOST_70P_CRUSH_CHANCE_TEMPLATE = {"BOOST_70P_CRUSH_CHANCE_1.png"}
config.BOOST_17P_BASE_SPEED_TEMPLATE = {"BOOST_17P_BASE_SPEED_1.png"}
config.BOOST_GOLD_COIN_MAGIC_TEMPLATE = {"BOOST_GOLD_COIN_MAGIC_1.png"}
config.BOOST_M30P_COLLISION_DAMAGE_TEMPLATE = {"BOOST_M30P_COLLISION_DAMAGE_1.png"}
config.BOOST_20P_HP_FROM_POTIONS_TEMPLATE = {"BOOST_20P_HP_FROM_POTIONS_1.png"}
config.BOOST_MAGNETIC_AURA_TEMPLATE = {"BOOST_MAGNETIC_AURA_1.png"}
config.BOOST_2PIT_LIFTS_TEMPLATE = {"BOOST_2PIT_LIFTS_1.png"}

config.BOOST_TEMPLATES = {
    config.BOOST_DOUBLE_COINS_TEMPLATE,
    config.BOOST_15P_SCORE_BONUS_TEMPLATE,
    config.BOOST_M15P_HP_DRAIN_TEMPLATE,
    config.BOOST_REVIVE_ONCE_WITH_80HP_TEMPLATE,
    config.BOOST_70P_CRUSH_CHANCE_TEMPLATE,
    config.BOOST_17P_BASE_SPEED_TEMPLATE,
    config.BOOST_GOLD_COIN_MAGIC_TEMPLATE,
    config.BOOST_M30P_COLLISION_DAMAGE_TEMPLATE,
    config.BOOST_20P_HP_FROM_POTIONS_TEMPLATE,
    config.BOOST_MAGNETIC_AURA_TEMPLATE,
    config.BOOST_2PIT_LIFTS_TEMPLATE,
}

-- -------------------
-- STAGE MAP
-- -------------------
config.STAGE_TEMPLATES = {
    GAME_START = config.STAGE_GAME_START_TEMPLATE,
    GAME_RELAY = config.STAGE_GAME_RELAY_TEMPLATE,
    ANTI_BOT = config.STAGE_ANTI_BOT_TEMPLATE,
    CONNECTION_LOST = config.STAGE_CONNECTION_LOST_TEMPLATE,
    INACTIVE = config.STAGE_INACTIVE_TEMPLATE,
    GAME_COMPLETE = config.STAGE_GAME_COMPLETE_TEMPLATE,
    OVERTAKE_BREAK_SCORE = config.STAGE_OVERTAKE_BREAK_SCORE_TEMPLATE,
    MYSTERY_BOX = config.STAGE_MYSTERY_BOX_TEMPLATE,
    CONGRATULATIONS = config.STAGE_CONGRATULATIONS_TEMPLATE,
    RELIC_COMPLETE = config.STAGE_RELIC_COMPLETE_TEMPLATE,
    RELIC_CLAIM = config.STAGE_RELIC_CLAIM_TEMPLATE,
    TOO_MANY_TREASURES = config.STAGE_TOO_MANY_TREASURES_TEMPLATE,
    MAINMENU = config.STAGE_MAINMENU_TEMPLATE,
    PARTY_RUN = config.STAGE_PARTY_RUN_TEMPLATE,
    GAME_SETTINGS = config.STAGE_GAME_SETTINGS_TEMPLATE,
    PURCHASE_ITEM = config.STAGE_PURCHASE_ITEM_TEMPLATE,
    LEVEL_UP = config.STAGE_LEVEL_UP_TEMPLATE,
    DAILY_CHECKIN = config.STAGE_DAILY_CHECKIN_TEMPLATE,
    DAILY_CHECKIN_BOOST_SET = config.STAGE_DAILY_CHECKIN_BOOST_SET_TEMPLATE,
    DAILY_TREASURE = config.STAGE_DAILY_TREASURE_TEMPLATE,
    DAILY_NEW = config.STAGE_DAILY_NEW_TEMPLATE,
    ENTER_LEAGUE = config.STAGE_ENTER_LEAGUE_TEMPLATE,
    LEAGUE_RESULTS = config.STAGE_LEAGUE_RESULTS_TEMPLATE,
    PREVIOUS_RANK_RESULTS = config.STAGE_PREVIOUS_RANK_RESULTS_TEMPLATE,
}

config.STAGE_REGIONS = {
    MAINMENU = config.STAGE_MAINMENU_REGION,
    PARTY_RUN = config.STAGE_PARTY_RUN_REGION,
    GAME_SETTINGS = config.STAGE_GAME_SETTINGS_REGION,
    PURCHASE_ITEM = config.STAGE_PURCHASE_ITEM_REGION,
    GAME_START = config.STAGE_GAME_START_REGION,
    GAME_RELAY = config.STAGE_GAME_RELAY_REGION,
    GAME_COMPLETE = config.STAGE_GAME_COMPLETE_REGION,
    OVERTAKE_BREAK_SCORE = config.STAGE_OVERTAKE_BREAK_SCORE_REGION,
    MYSTERY_BOX = config.STAGE_MYSTERY_BOX_REGION,
    CONGRATULATIONS = config.STAGE_CONGRATULATIONS_REGION,
    LEVEL_UP = config.STAGE_LEVEL_UP_REGION,
    RELIC_COMPLETE = config.STAGE_RELIC_COMPLETE_REGION,
    RELIC_CLAIM = config.STAGE_RELIC_CLAIM_REGION,
    DAILY_CHECKIN = config.STAGE_DAILY_CHECKIN_REGION,
    DAILY_CHECKIN_BOOST_SET = config.STAGE_DAILY_CHECKIN_BOOST_SET_REGION,
    DAILY_TREASURE = config.STAGE_DAILY_TREASURE_REGION,
    DAILY_NEW = config.STAGE_DAILY_NEW_REGION,
    ENTER_LEAGUE = config.STAGE_ENTER_LEAGUE_REGION,
    LEAGUE_RESULTS = config.STAGE_LEAGUE_RESULTS_REGION,
    ANTI_BOT = config.STAGE_ANTI_BOT_REGION,
    CONNECTION_LOST = config.STAGE_CONNECTION_LOST_REGION,
    INACTIVE = config.STAGE_INACTIVE_REGION,
    PREVIOUS_RANK_RESULTS = config.STAGE_PREVIOUS_RANK_RESULTS_REGION,
    TOO_MANY_TREASURES = config.STAGE_TOO_MANY_TREASURES_REGION,
}

-- -------------------
-- DETECTION GROUPS
-- -------------------
config.DETECTION_ALWAYS_STAGES = {
    "CONNECTION_LOST",
    "INACTIVE",
    "ANTI_BOT"
}

config.DETECTION_GROUP_PRE_GAME = {
    "CONGRATULATIONS",
    "LEVEL_UP",
    "RELIC_COMPLETE",
    "RELIC_CLAIM",
    "DAILY_CHECKIN",
    "DAILY_CHECKIN_BOOST_SET",
    "DAILY_TREASURE",
    "DAILY_NEW",
    "ENTER_LEAGUE",
    "LEAGUE_RESULTS",
    "PREVIOUS_RANK_RESULTS",
    "TOO_MANY_TREASURES",
    "PARTY_RUN",
    "GAME_SETTINGS",
    "MAINMENU",
    "PURCHASE_ITEM",
}

config.DETECTION_GROUP_IN_GAME = {
    "PURCHASE_ITEM", -- Retry Play without buying again if the transition was missed.
    "GAME_START",
    "GAME_RELAY",
    "GAME_COMPLETE",
}

config.DETECTION_GROUP_POST_GAME = {
    "ANTI_BOT",
    "OVERTAKE_BREAK_SCORE",
    "MYSTERY_BOX",
    "MAINMENU",
}

config.DETECTION_GROUPS = {
    PRE_GAME = config.DETECTION_GROUP_PRE_GAME,
    IN_GAME = config.DETECTION_GROUP_IN_GAME,
    POST_GAME = config.DETECTION_GROUP_POST_GAME,
}

config.DETECTION_RECOVERY_SCAN_INTERVAL = {
    PRE_GAME = 10.0,  -- seconds
    IN_GAME = 10.0,  -- seconds
    POST_GAME = 10.0,  -- seconds
}

-- -------------------
-- ITEM COORDINATES
-- -------------------
config.START_BUTTON = {955, 650}
config.PLAY_BUTTON = {895, 620}
config.FAST_START_ITEM = {235, 600}
config.COOKIE_RELAY_ITEM = {385, 600}
config.RANDOM_BOOST_ITEM = {535, 600}
config.PURCHASE_BUTTON = {925, 295}
config.MULTI_PURCHASE_BUTTON = {1100, 195}
config.MULTI_BUY_BUTTON = {640, 587}
config.FAST_START_USE_BUTTON = {655, 340}
config.COOKIE_RELAY_USE_BUTTON = {655, 340}
config.COMPLETE_FINISH_BUTTON = {460, 625}
config.ACCEPT_MYSTERY_BOX_BUTTON = {650, 645}
config.ACCEPT_CONGRATULATIONS_BUTTON = {640, 565}
config.ACCEPT_LEVEL_UP_BUTTON = {640, 640}
config.ACCEPT_DAILY_CHECKIN_BUTTON = {640, 660}
config.ACCEPT_DAILY_CHECKIN_BOOST_SET_BUTTON = {640, 568}
config.ACCEPT_DAILY_TREASURE_BUTTON = {650, 570}
config.ACCEPT_DAILY_NEW_BUTTON = {1128, 74}
config.ACCEPT_ENTER_LEAGUE_BUTTON = {640, 460}
config.ACCEPT_LEAGUE_RESULTS_BUTTON = {640, 610}
config.ACCEPT_PREVIOUS_RANK_RESULTS_BUTTON = {640, 615}
config.ACCEPT_TOO_MANY_TREASURES_BUTTON = {640, 545}
config.ACCEPT_OVERTAKE_BREAK_SCORE_BUTTON = {465, 640}
config.RELIC_COMPLETE_BUTTON = {530, 110}
config.RELIC_CLAIM_BUTTON = {640, 580}
config.RELIC_CLOSE_BUTTON = {1076, 154}
config.CONNECTION_LOST_RELOAD_BUTTON = {640, 460}
config.INACTIVE_RELOAD_BUTTON = {640, 460}
config.MAIL_BOX_BUTTON = {686, 677}
config.MAIL_BOX_LIVES_TAB_BUTTON = {630, 148}
config.MAIL_BOX_CLOSE_BUTTON = {1130, 87}
config.QUICK_RECEIVE_AND_SEND_LIVES_BUTTON = {652, 612}
config.ACCEPT_ALL_LIVES_RECEIVED_AND_SENT_BUTTON = {640, 462}
config.CONFIRM_SEND_LIFE_BUTTON = {797, 460}
config.CLOSE_SEND_LIFE_DIALOG_BUTTON = {645, 463}
config.LEADERBOARD_TOP_POSITION = {435, 260}
config.LEADERBOARD_BOTTOM_POSITION = {435, 620}
config.CLOSE_ANNOUNCEMENT_DIALOG_BUTTON = {1127, 66}
config.EXIT_PARTY_RUN_MODE_BUTTON = {1214, 89}
config.EXIT_GAME_SETTINGS_BUTTON = {1116, 98}

-- -------------------
-- ANTI-BOT CAPTCHA
-- -------------------
config.ANTI_BOT_CARD_POS_1 = {346, 179}
config.ANTI_BOT_CARD_POS_2 = {542, 179}
config.ANTI_BOT_CARD_POS_3 = {738, 179}
config.ANTI_BOT_CARD_POS_4 = {346, 435}
config.ANTI_BOT_CARD_POS_5 = {542, 435}
config.ANTI_BOT_CARD_POS_6 = {738, 435}
config.ANTI_BOT_CARD_WIDTH = 183
config.ANTI_BOT_CARD_HEIGHT = 241

return config
